' Project name:         Random Swap Project
' Project purpose:      Displays the lowest and highest of two random integers generated by the computer
' Created/revised by:   jake gudenkauf on <current date>

Option Explicit On
Option Strict On
Option Infer Off

Public Class MainForm

    Private Sub exitButton_Click(sender As Object, e As EventArgs) Handles exitButton.Click
        Me.Close()
    End Sub

    Private Sub generateButton_Click(sender As Object, e As EventArgs) Handles generateButton.Click
        'generate random numbers

        'declare variables
        Dim lownum As Integer
        Dim highnum As Integer
        Dim randomgen As New Random

        lownum = randomgen.Next(1, 251)
        highnum = randomgen.Next(1, 251)

        'swap numbers if necessary
        If lownum > highnum Then
            Dim temp As Integer
            temp = lownum
            lownum = highnum
            highnum = temp
        End If

        'display
        lowLabel.Text = Convert.ToString(lownum)
        highLabel.Text = Convert.ToString(highnum)
    End Sub
End Class
